### ISSUE TITLE
create helpers.js in utils 

### ISSUE THREAD

**Issue by mdkgray** [mdkgray/check-a-tradie#14]

**Comment by kreatifbob** [comment]
Has been created but requires updating

**Comment by kreatifbob** [comment]
The following is from Mini Project, do we even need these in our helpers.js?????

module.exports = {
  format_date: (date) => {
    // Format date as MM/DD/YYYY
    return date.toLocaleDateString();
  },
  format_amount: (amount) => {
    // format large numbers with commas
    return parseInt(amount).toLocaleString();
  },
  get_emoji: () => {
    const randomNum = Math.random();

    // Return a random emoji
    if (randomNum > 0.7) {
      return `<span for="img" aria-label="lightbulb">💡</span>`;
    } else if (randomNum > 0.4) {
      return `<span for="img" aria-label="laptop">💻</span>`;
    } else {
      return `<span for="img" aria-label="gear">⚙️</span>`;
    }
  },
};

**Comment by mdkgray** [comment]
No I dont think so I just added it in in case we did. Will most likely delete the file soon
